In [1]:
import pandas as pd

In [2]:
raw_path = './raw_csv'
cleaned_path = './cleaned_csv'

### พิกัด

In [3]:
latlong = pd.read_csv('{}/latlong.csv'.format(raw_path))
latlong.head()

,AD_LEVEL,TA_ID,TAMBON_T,TAMBON_E,AM_ID,AMPHOE_T,AMPHOE_E,CH_ID,CHANGWAT_T,CHANGWAT_E,LAT,LONG
0,4,910106,ต. เกาะสาหร่าย,Ko Sarai,9101,NaN,Mueang Satun,91,จ. สตูล,Satun,6.546,99.706
1,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.646,101.171
2,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.645,101.170
3,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.649,101.174
4,4,210114,ต. มาบตาพุด,Maptaphut,2101,อ. เมืองระยอง,Mueang Rayong,21,จ. ระยอง,Rayong,12.644,101.169

In [4]:
province = latlong['CHANGWAT_T'].unique()
province = [p.replace('จ. ', '') for p in province]
province

['สตูล',
 'ระยอง',
 'ชุมพร',
 'มหาสารคาม',
 'สุราษฎร์ธานี',
 'ชลบุรี',
 'ตรัง',
 'จันทบุรี',
 'พังงา',
 'ตราด',
 'ระนอง',
 'ภูเก็ต',
 'กระบี่',
 'กรุงเทพมหานคร',
 'นครศรีธรรมราช',
 'สมุทรสาคร',
 'พระนครศรีอยุธยา',
 'ลพบุรี',
 'สมุทรปราการ',
 'อ่างทอง',
 'ปัตตานี',
 'เชียงใหม่',
 'ชัยนาท',
 'นนทบุรี',
 'อุตรดิตถ์',
 'ขอนแก่น',
 'นครสวรรค์',
 'เพชรบุรี',
 'สิงห์บุรี',
 'สมุทรสงคราม',
 'ราชบุรี',
 'นครนายก',
 'สระบุรี',
 'นครปฐม',
 'กาญจนบุรี',
 'ปทุมธานี',
 'พิษณุโลก',
 'ฉะเชิงเทรา',
 'เชียงราย',
 'สงขลา',
 'ลำพูน',
 'หนองคาย',
 'อุบลราชธานี',
 'สุโขทัย',
 'พะเยา',
 'อุทัยธานี',
 'แพร่',
 'เพชรบูรณ์',
 'แม่ฮ่องสอน',
 'บุรีรัมย์',
 'พิจิตร',
 'น่าน',
 'ยะลา',
 'สุพรรณบุรี',
 'นครราชสีมา',
 'ปราจีนบุรี',
 'ตาก',
 'ร้อยเอ็ด',
 'นครพนม',
 'มุกดาหาร',
 'สระแก้ว',
 'อุดรธานี',
 'ลำปาง',
 'ศรีสะเกษ',
 'ยโสธร',
 'พัทลุง',
 'นราธิวาส',
 'เลย',
 'กาฬสินธุ์',
 'สุรินทร์',
 'ประจวบคีรีขันธ์',
 'ชัยภูมิ',
 'สกลนคร',
 'กำแพงเพชร',
 'อำนาจเจริญ',
 'หนองบัวลำภู',
 'บึงกาฬ']

In [5]:
latlong['province'] = latlong['CHANGWAT_T'].apply(lambda x: x.replace('จ. ', ''))

In [6]:
district = latlong[latlong['AMPHOE_T'].notnull()]['AMPHOE_T'].unique()
district = [d.replace('อ. ', '') for d in district]
district

['เมืองระยอง',
 'เมืองชุมพร',
 'สวี',
 'เมืองมหาสารคาม',
 'เกาะสมุย',
 'สัตหีบ',
 'หาดสำราญ',
 'ปะทิว',
 'ทุ่งตะโก',
 'เมืองสตูล',
 'แหลมสิงห์',
 'คุระบุรี',
 'เกาะกูด',
 'สุขสำราญ',
 'กันตัง',
 'ดอนสัก',
 'เมืองภูเก็ต',
 'สิเกา',
 'ศรีราชา',
 'เมืองกระบี่',
 'อ่าวลึก',
 'เมืองระนอง',
 'ถลาง',
 'บางละมุง',
 'แกลง',
 'กะเปอร์',
 'เกาะลันตา',
 'เกาะพะงัน',
 'ขลุง',
 'เขต พระนคร',
 'เกาะยาว',
 'ปะเหลียน',
 'เหนือคลอง',
 'ท่าใหม่',
 'เกาะช้าง',
 'เขต ดุสิต',
 'เขต ป้อมปราบศัตรูพ่าย',
 'เขต สัมพันธวงศ์',
 'เมืองชลบุรี',
 'เขต บางรัก',
 'หลังสวน',
 'ขนอม',
 'เมืองสมุทรสาคร',
 'เขต ธนบุรี',
 'เขต คลองสาน',
 'เขต ภาษีเจริญ',
 'เสนา',
 'เขต บางกอกใหญ่',
 'เมืองลพบุรี',
 'พระประแดง',
 'เมืองอ่างทอง',
 'เขต ราชเทวี',
 'เขต ตลิ่งชัน',
 'พระนครศรีอยุธยา',
 'เขต ปทุมวัน',
 'เมืองปัตตานี',
 'เมืองเชียงใหม่',
 'วัดสิงห์',
 'เขต บางกอกน้อย',
 'เขต บางคอแหลม',
 'บางบัวทอง',
 'เมืองชัยนาท',
 'ลับแล',
 'เขต คลองเตย',
 'เขต สาทร',
 'บ้านไผ่',
 'เขต วัฒนา',
 'เมืองนครศรีธรรมราช',
 'ชุมแสง',
 'เขต บางพลัด',
 'ปากเกร็ด',
 'เมืองเพชรบุรี',
 'เมืองสิงห์บุรี',
 'บางคนที',
 'บ้านโป่ง',
 'เมืองนครนายก',
 'ผักไห่',
 'แก่งคอย',
 'เขต จอมทอง',
 'นครชัยศรี',
 'บางกรวย',
 'อัมพวา',
 'พนัสนิคม',
 'ท่ามะกา',
 'เมืองปทุมธานี',
 'เมืองสระบุรี',
 'เมืองพิษณุโลก',
 'บางไทร',
 'เมืองฉะเชิงเทรา',
 'ไชโย',
 'เมืองเชียงราย',
 'โพธาราม',
 'กระแสสินธุ์',
 'สันกำแพง',
 'สามโคก',
 'เมืองสมุทรปราการ',
 'บ้านลาด',
 'เมืองนนทบุรี',
 'ท่าเรือ',
 'หนองจิก',
 'เสาไห้',
 'เมืองสมุทรสงคราม',
 'หาดใหญ่',
 'หางดง',
 'ป่าซาง',
 'บางปะหัน',
 'เมืองพังงา',
 'พร้าว',
 'บ้านแพรก',
 'เมืองหนองคาย',
 'เมืองอุบลราชธานี',
 'เมืองสุโขทัย',
 'เมืองนครปฐม',
 'ละงู',
 'เมืองพะเยา',
 'กระทุ่มแบน',
 'เมืองจันทบุรี',
 'ดอยสะเก็ด',
 'มหาราช',
 'ตะกั่วป่า',
 'อุทัย',
 'ระโนด',
 'เมืองลำพูน',
 'เขต ห้วยขวาง',
 'หนองขาหย่าง',
 'เมืองสุราษฎร์ธานี',
 'ยะหริ่ง',
 'บางบาล',
 'บางปะอิน',
 'แม่วาง',
 'สารภี',
 'เขต ยานนาวา',
 'เมืองแพร่',
 'โพธิ์ทอง',
 'หล่มสัก',
 'เมืองแม่ฮ่องสอน',
 'ดำเนินสะดวก',
 'นครหลวง',
 'เขต ราษฎร์บูรณะ',
 'เมืองบุรีรัมย์',
 'ป่าโมก',
 'สันทราย',
 'แม่ริม',
 'สูงเม่น',
 'ตะพานหิน',
 'เขต หลักสี่',
 'เขต ลาดพร้าว',
 'เมืองสงขลา',
 'เมืองน่าน',
 'บางมูลนาก',
 'มายอ',
 'สวรรคโลก',
 'ไม้แก่น',
 'หนองแซง',
 'สามพราน',
 'รามัน',
 'เกาะสีชัง',
 'วิเศษชัยชาญ',
 'เดิมบางนางบวช',
 'เมืองสุพรรณบุรี',
 'บางคล้า',
 'เมืองยะลา',
 'บางใหญ่',
 'บ้านโพธิ์',
 'เมืองอุทัยธานี',
 'เมืองตรัง',
 'สูงเนิน',
 'วารินชำราบ',
 'ศรีสำโรง',
 'ยะรัง',
 'เมืองเพชรบูรณ์',
 'หนองม่วงไข่',
 'บ้านหมี่',
 'ปากท่อ',
 'ท่าม่วง',
 'บ้านแหลม',
 'พานทอง',
 'จุฬาภรณ์',
 'หนองแค',
 'สทิงพระ',
 'เมืองปราจีนบุรี',
 'ดอยหล่อ',
 'เมืองตาก',
 'ภาชี',
 'เมืองราชบุรี',
 'ท่าช้าง',
 'พนมไพร',
 'สิงหนคร',
 'พิบูลมังสาหาร',
 'พุนพิน',
 'เขต ดินแดง',
 'เมืองนครราชสีมา',
 'ธาตุพนม',
 'เมืองนครพนม',
 'แม่แตง',
 'พระสมุทรเจดีย์',
 'ทุ่งสง',
 'พรหมบุรี',
 'เขต พญาไท',
 'สระโบสถ์',
 'สันป่าตอง',
 'เมืองมุกดาหาร',
 'อรัญประเทศ',
 'เขต บางแค',
 'สายบุรี',
 'ปะนาเระ',
 'ท่ายาง',
 'ท่าวุ้ง',
 'เมืองอุดรธานี',
 'เชียรใหญ่',
 'งาว',
 'วังยาง',
 'เขต คลองสามวา',
 'ดอนพุด',
 'กุมภวาปี',
 'บางปะกง',
 'ขุขันธ์',
 'ปักธงชัย',
 'เมืองพิจิตร',
 'โคกโพธิ์',
 'เมืองลำปาง',
 'คลองเขื่อน',
 'เชียงคำ',
 'จะนะ',
 'แม่จัน',
 'หนองฉาง',
 'เมืองยโสธร',
 'ว่านใหญ่',
 'นาโยง',
 'เมืองพัทลุง',
 'วัดเพลง',
 'เมืองร้อยเอ็ด',
 'บ้านหมอ',
 'บางกล่ำ',
 'ศรีสมเด็จ',
 'หัวไทร',
 'เมืองนครสวรรค์',
 'เขต ลาดกระบัง',
 'เฉลิมพระเกียรติ',
 'แสวงหา',
 'ลำปลายมาศ',
 'เขาย้อย',
 'บ้านแพ้ว',
 'กำแพงแสน',
 'ศรีมหาโพธิ',
 'ดอนตูม',
 'ทัพทัน',
 'อุทุมพรพิสัย',
 'คลองใหญ่',
 'ควนโดน',
 'กงไกรลาศ',
 'บางปลาม้า',
 'ปากพลี',
 'เขต ทุ่งครุ',
 'พระพุทธบาท',
 'เขต บางกะปิ',
 'ปากพนัง',
 'ห้วยยอด',
 'อินทร์บุรี',
 'เมืองนราธิวาส',
 'เขต สายไหม',
 'ท่าวังผา',
 'ปากพะยูน',
 'เก้าเลี้ยว',
 'ไชยา',
 'เขต ประเวศ',
 'หล่มเก่า',
 'จังหาร',
 'เมืองเลย',
 'โคกสำโรง',
 'ร่องคำ',
 'โนนสูง',
 'เขต บางซื่อ',
 'เวียงหนองล่อง',
 'ห้วยราช',
 'ประจันตคาม',
 'เขต พระโขนง',
 'บางบ่อ',
 'นาดูน',
 'พุทธมณฑล',
 'บางซ้าย',
 'สามโก้',
 'เสลภูมิ',
 'บ้านค่าย',
 'เมืองสุรินทร์',
 'ภูเวียง',
 'บึงบูรพ์',
 'สองพี่น้อง',
 'ภูเพียง',
 'กระบุรี',
 'สรรคบุรี',
 'บ้านนา',
 'ไชยปราการ',
 'สอง',
 'เมืองอุตรดิตถ์',
 'สุวรรณภูมิ',
 'ลาดหลุมแก้ว',
 'นาทวี',
 'เมืองประจวบคีรีขันธ์',
 'เรณูนคร',
 'ธัญบุรี',
 'ค่ายบางระจัน',
 'นาหว้า',
 'กู่แก้ว',
 'บางแพ',
 'บางระจัน',
 'ภูผาม่าน',
 'เขาวง',
 'ทุ่งหว้า',
 'คอนสาร',
 'เขื่องใน',
 'แม่ใจ',
 'หนองสูง',
 'ชัยบาดาล',
 'เมืองศรีสะเกษ',
 'เกาะคา',
 'สำโรงทาบ',
 'เขต หนองจอก',
 'เชียงขวัญ',
 'เขต บางนา',
 'ภูกามยาว',
 'โพธิ์ศรีสุวรรณ',
 'ธวัชบุรี',
 'เขต หนองแขม',
 'วังน้อย',
 'ห้วยแถลง',
 'พรหมคีรี',
 'สรรพยา',
 'ดอกคำใต้',
 'ภูซาง',
 'เขาชัยสน',
 'โกรกพระ',
 'ร้องกวาง',
 'ศรีนครินทร์',
 'พยัคฆภูมิพิสัย',
 'รัษฎา',
 'คำชะอี',
 'สำโรง',
 'เมืองสกลนคร',
 'นางรอง',
 'ปัว',
 'เขต วังทองหลาง',
 'ทุ่งเขาหลวง',
 'เมืองกำแพงเพชร',
 'บางเลน',
 'พนมทวน',
 'บ้านดุง',
 'พล',
 'เขต บางเขน',
 'บาเจาะ',
 'แม่สอด',
 'ยี่งอ',
 'ตระการพืชผล',
 'กันทรวิชัย',
 'สากเหล็ก',
 'ละอุ่น',
 'สุไหงโก-ลก',
 'อาจสามารถ',
 'ยะหา',
 'ตากใบ',
 'ลาดบัวหลวง',
 'คำเขื่อนแก้ว',
 'ย่านตาขาว',
 'วิหารแดง',
 'ท่าอุเทน',
 'จอมพระ',
 'เขต ทวีวัฒนา',
 'ปาย',
 'สหัสขันธ์',
 'ตาคลี',
 'หนองกี่',
 'ชุมแพ',
 'บ้านเขว้า',
 'ควนขนุน',
 'กาญจนดิษฐ์',
 'ราษีไศล',
 'ฉวาง',
 'เมืองตราด',
 'กุฉินารายณ์',
 'นิคมน้ำอูน',
 'ขุนหาญ',
 'จตุรพักตรพิมาน',
 'แหลมงอบ',
 'อู่ทอง',
 'บางกระทุ่ม',
 'ห้วยเม็ก',
 'โกสุมพิสัย',
 'เชียงยืน',
 'ยางสีสุราช',
 'สนม',
 'บ้านบึง',
 'วานรนิวาส',
 'กะทู้',
 'เปือยน้อย',
 'ไพรบึง',
 'โพธิ์ชัย',
 'พาน',
 'เมยวดี',
 'หนองกุงศรี',
 'กะพ้อ',
 'ชนบท',
 'วาริชภูมิ',
 'ศรีมโหสถ',
 'แม่ทะ',
 'แม่ลาน',
 'แว้ง',
 'กันทรารมย์',
 'โนนศิลา',
 'ท่าศาลา',
 'ฆ้องชัย',
 'ชะอำ',
 'พยุหะคีรี',
 'แม่สาย',
 'แม่ออน',
 'ทับสะแก',
 'เมืองอำนาจเจริญ',
 'นาวัง',
 'วังหิน',
 'ชะอวด',
 'หนองบัว',
 'นาแก',
 'ดอยเต่า',
 'ทุ่งยางแดง',
 'พนมสารคาม',
 'พระพรหม',
 'โพนทอง',
 'หนองหาน',
 'มหาชนะชัย',
 'ลืออำนาจ',
 'ท่าบ่อ',
 'บรบือ',
 'คอนสวรรค์',
 'ซำสูง',
 'ศรีประจันต์',
 'บางแก้ว',
 'ยางตลาด',
 'ทุ่งฝน',
 'ปราสาท',
 'สร้างคอม',
 'สุวรรณคูหา',
 'พรเจริญ',
 'คลองหลวง',
 'วาปีปทุม',
 'จะแนะ',
 'ลำลูกกา',
 'บางเสาธง',
 'โนนนารายณ์',
 'เขต บึงกุ่ม',
 'เมืองกาฬสินธุ์',
 'ไทรน้อย',
 'ชำนิ',
 'สุไหงปาดี',
 'นาหม่อม',
 'มโนรมย์',
 'ยางชุมน้อย',
 'ศรีเมืองใหม่',
 'ท่าปลา',
 'หนองฮี',
 'เขต สวนหลวง',
 'นาเชือก',
 'หนองบุญมาก',
 'บัวใหญ่',
 'สิรินธร',
 'พรหมพิราม',
 'พระยืน',
 'เมืองจันทร์',
 'คีรีรัฐนิคม',
 'เขต มีนบุรี',
 'บางพลี',
 'โชคชัย',
 'นาคู',
 'แม่ลาว',
 'กระนวน',
 'บ้านนาเดิม',
 'สมเด็จ',
 'พยุห์',
 'แกดำ',
 'ศรีเชียงใหม่',
 'ปรางค์กู่',
 'บ้านด่าน',
 'องครักษ์',
 'ชื่นชม',
 'สีดา',
 'กงหรา',
 'เขต คันนายาว',
 'กมลาไสย',
 'หนองหงส์',
 'โพทะเล',
 'บ้านเหลื่อม',
 'น้ำพอง',
 'เชียงกลาง',
 'เวียงสา',
 'ห้วยทับทัน',
 'บ้านใหม่ไชยพจน์',
 'คำม่วง',
 'เมืองชัยภูมิ',
 'บ้านสร้าง',
 'หนองโดน',
 'เทิง',
 'เมืองสรวง',
 'ปะคำ',
 'โพธิ์ตาก',
 'ลาดยาว',
 'ตรอน',
 'ครบุรี',
 'ประโคนชัย',
 'กันทรลักษ์',
 'เขต สะพานสูง',
 'ม่วงสามสิบ',
 'ดอนตาล',
 'กระสัง',
 'แม่ทา',
 'ศิลาลาด',
 'ศรีสาคร',
 'พรานกระต่าย',
 'กบินทร์บุรี',
 'ศรีนคร',
 'บ้านผือ',
 'เหล่าเสือโก้ก',
 'นายายอาม',
 'ศรีสัชนาลัย',
 'ศรีรัตนะ',
 'กุยบุรี',
 'โนนดินแดง',
 'ลอง',
 'หัวตะพาน',
 'แวงใหญ่',
 'หนองสองห้อง',
 'คีรีมาศ',
 'บ้านโฮ่ง',
 'สามชุก',
 'เด่นชัย',
 'อุบลรัตน์',
 'ประทาย',
 'ป่าแดด',
 'เขาสวนกวาง',
 'ลำสนธิ',
 'ศรีบุญเรือง',
 'หันคา',
 'ด่านซ้าย',
 'ร่อนพิบูลย์',
 'ดงเจริญ',
 'ลำทะเมนชัย',
 'ปลาปาก',
 'สว่างแดนดิน',
 'สตึก',
 'รัตนบุรี',
 'พุทไธสง',
 'ควนเนียง',
 'ด่านขุนทด',
 'รัตนวาปี',
 'รือเสาะ',
 'เขวาสินรินทร์',
 'ปทุมรัตต์',
 'เมืองหนองบัวลำภู',
 'แม่อาย',
 'บ้านนาสาร',
 'ป่าพยอม',
 'บ้านแพง',
 'บางน้ำเปรี้ยว',
 'โคกศรีสุพรรณ',
 'สีชมพู',
 'ขามสะแกแสง',
 'หนองเรือ',
 'โพนทราย',
 'หัวหิน',
 'น้ำเกลี้ยง',
 'โนนไทย',
 'คลองขลุง',
 'ปราณบุรี',
 'สีคิ้ว',
 'เขต จตุจักร',
 'เวียงป่าเป้า',
 'ห้างฉัตร',
 'ศีขรภูมิ',
 'วังเหนือ',
 'ทรายมูล',
 'ทับปุด',
 'ราชสาส์น',
 'ขามทะเลสอ',
 'เบญจลักษ์',
 'เมืองขอนแก่น',
 'พรรณานิคม',
 'โนนสุวรรณ',
 'ชุมพลบุรี',
 'รัตภูมิ',
 'นิคมคำสร้อย',
 'ท่าฉาง',
 'บรรพตพิสัย',
 'ท่าแซะ',
 'กรงปีนัง',
 'โพธิ์ไทร',
 'เขต บางบอน',
 'บัวลาย',
 'เต่างอย',
 'ลำดวน',
 'เกษตรวิสัย',
 'กุดชุม',
 'ศรีธาตุ',
 'เสนางคนิคม',
 'เดชอุดม',
 'ภูสิงห์',
 'ลานสกา',
 'พนม',
 'บ้านไร่',
 'นาโพธิ์',
 'บางสะพาน',
 'ดอนมดแดง',
 'โนนสัง',
 'ท่าแพ',
 'ท่าตูม',
 'พิชัย',
 'น้ำโสม',
 'แวงน้อย',
 'ดอนจาน',
 'ป่าติ้ว',
 'เมืองกาญจนบุรี',
 'บางสะพานน้อย',
 'หนองบัวระเหว',
 'นากลาง',
 'วัดโบสถ์',
 'ระแงะ',
 'ไทยเจริญ',
 'เขต ดอนเมือง',
 'ปากคาด',
 'โนนคูณ',
 'ท่าชนะ',
 'บำเหน็จณรงค์',
 'เชียงคาน',
 'โนนแดง',
 'วังสะพุง',
 'ตาลสุม',
 'นามน',
 'บ้านฝาง',
 'ตากฟ้า',
 'คลองหอยโข่ง',
 'หนองวัวซอ',
 'บึงสามัคคี',
 'ห้วยผึ้ง',
 'พนา',
 'บ้านตาขุน',
 'เขมราฐ',
 'ค้อวัง',
 'หนองม่วง',
 'คง',
 'ทุ่งศรีอุดม',
 'แก้งคร้อ',
 'พิปูน',
 'ช้างกลาง',
 'บ้านกรวด',
 'ปทุมราชวงศา',
 'ท่าหลวง',
 'จักราช',
 'หนองเสือ',
 'ประจักษ์ศิลปาคม',
 'ภูหลวง',
 'เขาฉกรรจ์',
 'หนองนาคำ',
 'บึงกาฬ',
 'โนนสะอาด',
 'กาบเชิง',
 'มะขาม',
 'บ้านฉาง',
 'ทุ่งเสลี่ยม',
 'บ้านหลวง',
 'นครไทย',
 'สระใคร',
 'สิชล',
 'เถิน',
 'ศรีสงคราม',
 'สะเดา',
 'สว่างอารมณ์',
 'ชุมพวง',
 'เวียงชัย',
 'ธารโต',
 'พิมาย',
 'หนองพอก',
 'เฝ้าไร่',
 'ฝาง',
 'บ่อทอง',
 'เกษตรสมบูรณ์',
 'โพนนาแก้ว',
 'ตะโหมด',
 'วชิรบารมี',
 'พระทองคำ',
 'พังโคน',
 'บ้านแท่น',
 'บึงสามพัน',
 'ท่าตะโก',
 'ดอนเจดีย์',
 'ละแม',
 'ท่าคันโท',
 'พญาเม็งราย',
 'ลานกระบือ',
 'ละหานทราย',
 'กุดข้าวปุ้น',
 'วังจันทร์',
 'อากาศอำนวย',
 'พลับพลาชัย',
 'แคนดง',
 'กุดรัง',
 'ซับใหญ่',
 'บัวเชด',
 'โพนพิสัย',
 'สามเงา',
 'นาตาล',
 'โพธิ์ประทับช้าง',
 'หนองมะโมง',
 'นาด้วง',
 'โพนสวรรค์',
 'เขาค้อ',
 'โขงเจียม',
 'พระแสง',
 'เวียงเก่า',
 'พัฒนานิคม',
 'โกสัมพีนคร',
 'บางระกำ',
 'วังทอง',
 'แก้งสนามนาง',
 'คูเมือง',
 'บึงนาราง',
 'สามง่าม',
 'บ้านแฮด',
 'โคกสูง',
 'จัตุรัส',
 'ศรีเทพ',
 'ภูเขียว',
 'บึงโขงหลง',
 'เซกา',
 'จุน',
 'เขต บางขุนเทียน',
 'ขาณุวรลักษบุรี',
 'แจ้ห่ม',
 'เมืองสระแก้ว',
 'เชียงแสน',
 'ศรีณรงค์',
 'พนมดงรัก',
 'เพ็ญ',
 'บ้านตาก',
 'วัฒนานคร',
 'วังโป่ง',
 'สังคม',
 'ดงหลวง',
 'โซ่พิสัย',
 'หนองแสง',
 'หนองไผ่',
 'เชียงของ',
 'เลิงนกทา',
 'เวียงแหง',
 'สามชัย',
 'สว่างวีระวงศ์',
 'สังขะ',
 'เทพา',
 'วังวิเศษ',
 'จอมทอง',
 'วังม่วง',
 'เนินสง่า',
 'เวียงสระ',
 'นาจะหลวย',
 'คลองหาด',
 'บ้านธิ',
 'สันติสุข',
 'ศรีบรรพต',
 'นิคมพัฒนา',
 'วิเชียรบุรี',
 'ศรีวิไล',
 'นบพิตำ',
 'วังทรายพูน',
 'ผาขาว',
 'นาดี',
 'โคกโพธิ์ไชย',
 'นาน้อย',
 'ส่องดาว',
 'ถ้ำพรรณรา',
 'ด่านมะขามเตี้ย',
 'แม่จริม',
 'ตะกั่วทุ่ง',
 'ชานุมาน',
 'กุดจับ',
 'วังสามหมอ',
 'นาบอน',
 'เจริญศิลป์',
 'เคียนซา',
 'เมืองยาง',
 'วังเจ้า',
 'เจาะไอร้อง',
 'ป่าบอน',
 'นาเยีย',
 'น้ำยืน',
 'ลำทับ',
 'ทรายทองวัฒนา',
 'ขุนตาล',
 'สุคิริน',
 'หนองหิน',
 'เทพารักษ์',
 'บ้านด่านลานหอย',
 'ฮอด',
 'อุ้มผาง',
 'ท่าลี่',
 'หนองใหญ่',
 'บุณฑริก',
 'แก่งหางแมว',
 'บ้านม่วง',
 'เขาสมิง',
 'แม่สรวย',
 'แปลงยาว',
 'มัญจาคีรี',
 'ลานสัก',
 'ทับคล้อ',
 'น้ำขุ่น',
 'ภูกระดึง',
 'ทุ่งใหญ่',
 'เขาคิชฌกูฏ',
 'สะบ้าย้อย',
 'หนองหญ้าไซ',
 'แม่ระมาด',
 'เวียงแก่น',
 'ปลวกแดง',
 'บันนังสตา',
 'พิบูลย์รักษ์',
 'ห้วยคต',
 'แม่พริก',
 'เนินขาม',
 'เอราวัณ',
 'ท้ายเหมือง',
 'เกาะจันทร์',
 'เนินมะปราง',
 'ปง',
 'ชนแดน',
 'ไชยวาน',
 'ดอยหลวง',
 'ไทรงาม',
 'สอยดาว',
 'แก่งกระจาน',
 'บางขัน',
 'วังชิ้น',
 'กะปง',
 'โคกเจริญ',
 'บ่อไร่',
 'ชุมตาบง',
 'ภูเรือ',
 'เบตง',
 'เวียงเชียงรุ้ง',
 'เลาขวัญ',
 'โป่งน้ำร้อน',
 'ปลายพระยา',
 'ไพศาลี',
 'นาหมื่น',
 'พบพระ',
 'จอมบึง',
 'เขาชะเมา',
 'วังน้ำเย็น',
 'แม่สะเรียง',
 'นายูง',
 'มะนัง',
 'ลี้',
 'บุ่งคล้า',
 'ควนกาหลง',
 'หนองหญ้าปล้อง',
 'นาทม',
 'คำตากล้า',
 'กุสุมาลย์',
 'ด่านช้าง',
 'สวนผึ้ง',
 'เสริมงาม',
 'แม่วงก์',
 'คลองท่อม',
 'สบปราบ',
 'ตาพระยา',
 'มวกเหล็ก',
 'ฟากท่า',
 'ห้วยกระเจา',
 'หนองบัวแดง',
 'ชัยบุรี',
 'ปากชม',
 'ทองแสนขัน',
 'วังน้ำเขียว',
 'ปางศิลาทอง',
 'ภูพาน',
 'สบเมย',
 'ชาติตระการ',
 'แม่ฟ้าหลวง',
 'นาแห้ว',
 'สามร้อยยอด',
 'บ้านคา',
 'หนองปรือ',
 'แม่ลาน้อย',
 'เสิงสาง',
 'กาบัง',
 'ภักดีชุมพล',
 'วังสมบูรณ์',
 'แม่แจ่ม',
 'ไทรโยค',
 'ปากช่อง',
 'เทพสถิต',
 'เขาพนม',
 'ทุ่งช้าง',
 'บ้านโคก',
 'พะโต๊ะ',
 'บ่อเกลือ',
 'สนามชัยเขต',
 'น้ำหนาว',
 'กุดบาก',
 'แม่เมาะ',
 'ทุ่งหัวช้าง',
 'เมืองปาน',
 'เชียงม่วน',
 'ทองผาภูมิ',
 'ขุนยวม',
 'สะเมิง',
 'เชียงดาว',
 'กัลยาณิวัฒนา',
 'สองแคว',
 'น้ำปาด',
 'ท่าสองยาง',
 'ศรีสวัสดิ์',
 'บ่อพลอย',
 'ปางมะผ้า',
 'วิภาวดี',
 'คลองลาน',
 'อมก๋อย',
 'แม่เปิน',
 'ท่าตะเกียบ',
 'สังขละบุรี']

In [7]:
latlong['district'] = latlong['AMPHOE_T'].apply(lambda x: x.replace('อ. ', '') if isinstance(x, str) else x)

In [8]:
latlong.to_csv('{}/latlong.csv'.format(cleaned_path), index=False)

### ข้าว ฯลฯ

In [9]:
rice = pd.read_csv('{}/rice.csv'.format(raw_path))
rice.head()

       พื้นที่   เนื้อที่ปลูก              ผลผลิต
0          NaN          (ไร่)                 NaN
1          NaN            NaN          (กิโลกรัม)
2   รวมทั้งหมด  96,845,157.10  125,234,998,062.90
3       กระบี่      10,722.50       11,344,464.00
4  เมืองกระบี่       2,417.00          557,125.00

In [10]:
rice_by_province = rice.loc[rice['พื้นที่'].isin(province)]
rice_by_province

             พื้นที่  เนื้อที่ปลูก            ผลผลิต
3             กระบี่     10,722.50     11,344,464.00
140    กรุงเทพมหานคร    162,066.60    111,014,755.05
336        กาญจนบุรี  2,070,235.42  6,538,199,900.30
623        กาฬสินธุ์  2,249,315.34  1,606,374,649.42
956        กำแพงเพชร  2,937,594.05  8,296,272,523.72
...              ...           ...               ...
15388     อำนาจเจริญ  1,131,497.18    385,416,911.25
15525       อุดรธานี  3,080,506.52  5,598,498,446.50
15857      อุตรดิตถ์    997,125.74    574,300,459.50
15961      อุทัยธานี  1,358,899.50  3,172,068,736.25
16126    อุบลราชธานี  4,645,249.89  2,388,256,852.00

[78 rows x 3 columns]

In [11]:
rice_by_province.to_csv('{}/rice_by_province.csv'.format(cleaned_path), index=False)

In [13]:
rice_by_district = rice.loc[rice['พื้นที่'].isin(district)]
rice_by_district

             พื้นที่ เนื้อที่ปลูก         ผลผลิต
4        เมืองกระบี่     2,417.00     557,125.00
25            เขาพนม     1,995.50   4,831,700.00
40         เกาะลันตา          309     865,450.00
49          คลองท่อม          842     348,862.00
58           อ่าวลึก     2,340.00     372,510.00
...              ...          ...            ...
16462         นาเยีย   112,336.00  51,510,080.00
16485          นาตาล    67,800.00  31,683,400.00
16493  เหล่าเสือโก้ก    93,627.50  37,649,198.50
16516  สว่างวีระวงศ์    55,847.50  30,651,350.00
16535        น้ำขุ่น    85,017.00  77,274,748.00

[864 rows x 3 columns]

In [14]:
rice_by_district.to_csv('{}/rice_by_district.csv'.format(cleaned_path), index=False)

### ไม้ผล ไม้ยืนต้น

In [15]:
fruit = pd.read_csv('{}/fruit.csv'.format(raw_path), names=['พื้นที่', 'เนื้อที่ยืนต้น ให้ผลผลิต (ไร่)', 'เนื้อที่ยืนต้น ยังไม่ให้ผลผลิต (ไร่)', 'รวม (ไร่)', 'ผลผลิตที่เก็บเกี่ยวได้ (กิโลกรัม)'])
fruit.head()

,พื้นที่,เนื้อที่ยืนต้น ให้ผลผลิต (ไร่),เนื้อที่ยืนต้น ยังไม่ให้ผลผลิต (ไร่),รวม (ไร่),ผลผลิตที่เก็บเกี่ยวได้ (กิโลกรัม)
0,พื้นที่,เนื้อที่ยืนต้นทั้งหมด,NaN,NaN,ผลผลิตที่เก็บเกี่ยวได้
1,NaN,(ไร่),NaN,NaN,(กิโลกรัม)
2,NaN,ให้ผลผลิต,ยังไม่ให้ผล,รวม (ไร่),NaN
3,NaN,NaN,NaN,NaN,NaN
4,รวมทั้งหมด,"30,798,933.73","9,135,129.23","39,934,062.96","35,876,338,291.57"

In [16]:
fruit_by_province = fruit.loc[fruit['พื้นที่'].isin(province)]
fruit_by_province

,พื้นที่,เนื้อที่ยืนต้น ให้ผลผลิต (ไร่),เนื้อที่ยืนต้น ยังไม่ให้ผลผลิต (ไร่),รวม (ไร่),ผลผลิตที่เก็บเกี่ยวได้ (กิโลกรัม)
5,กระบี่,"1,789,911.01","239,486.50","2,029,397.51","4,584,790,834.31"
140,กรุงเทพมหานคร,"5,637.25","6,896.50","12,533.75","16,885,878.00"
315,กาญจนบุรี,"175,705.00","95,394.38","271,099.38","279,031,267.33"
598,กาฬสินธุ์,"112,097.37","100,207.61","212,304.98","10,293,133.10"
791,กำแพงเพชร,"62,508.75","84,797.50","147,306.25","56,347,200.25"
...,...,...,...,...,...
12529,อำนาจเจริญ,"49,654.93","19,592.25","69,247.18","4,167,967.88"
12592,อุดรธานี,"300,168.86","261,385.69","561,554.55","298,971,565.05"
12886,อุตรดิตถ์,"91,402.75","71,410.59","162,813.34","54,403,437.50"
13022,อุทัยธานี,"37,505.50","32,142.78","69,648.28","24,417,730.50"
13175,อุบลราชธานี,"251,257.70","240,138.14","491,395.84","246,930,271.66"

In [17]:
fruit_by_province.to_csv('{}/fruit_by_province.csv'.format(cleaned_path), index=False)

In [18]:
fruit_by_district = fruit.loc[fruit['พื้นที่'].isin(district)]
fruit_by_district

,พื้นที่,เนื้อที่ยืนต้น ให้ผลผลิต (ไร่),เนื้อที่ยืนต้น ยังไม่ให้ผลผลิต (ไร่),รวม (ไร่),ผลผลิตที่เก็บเกี่ยวได้ (กิโลกรัม)
6,เมืองกระบี่,"194,375.50","13,058.50","207,434.00","179,081,953.00"
26,เขาพนม,"357,095.50","30,887.00","387,982.50","2,063,144,461.39"
38,เกาะลันตา,"57,111.01","9,343.00","66,454.01","47,274,543.94"
57,คลองท่อม,"395,447.00","37,293.00","432,740.00","428,089,974.05"
72,อ่าวลึก,"332,422.00","51,999.00","384,421.00","2,600.00"
...,...,...,...,...,...
13354,นาเยีย,"2,738.25","3,439.90","6,178.15","19,146,280.00"
13366,นาตาล,"1,070.60","1,970.50","3,041.10","147,482.00"
13369,มะขาม,97,0,97,0
13374,เหล่าเสือโก้ก,"3,336.25","1,388.00","4,724.25","1,507,894.97"
13383,น้ำขุ่น,"13,806.00","5,441.00","19,247.00","5,956,050.00"

In [19]:
fruit_by_district.to_csv('{}/fruit_by_district.csv'.format(cleaned_path), index=False)